config/routes.rb
Rails.application.routes.draw do
  root to: 'albums#index'

  resources :albums

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :albums, only: [:index, :show]
      resources :users, only: [:show] do
        resources :albums, only: [:index]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @photos = HTTParty.get("https://jsonplaceholder.typicode.com/photos#{params[:albumId]}")
    @users = HTTParty.get("https://jsonplaceholder.typicode.com/users/#{params[:id]}")
    @albums = HTTParty.get("https://jsonplaceholder.typicode.com/albums")
  end

  def show
    @album = HTTParty.get("https://jsonplaceholder.typicode.com/albums/#{params[:id]}")
    @photos = HTTParty.get("https://jsonplaceholder.typicode.com/photos#{params[:albumId]}")
    @user = HTTParty.get("https://jsonplaceholder.typicode.com/users/#{params[:id]}")
  end
end

app/controllers/api/v1/albums_controller.rb
class Api::V1::AlbumsController < Api::V1::BaseController
  def index
    render json: AlbumCall.new.users_album(params[:user_id])
  end

  def show
    render json: AlbumCall.new.album_item(params[:id])
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def show
    users = AlbumCall.new.all_users(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def show
    @photos = HTTParty.get('https://jsonplaceholder.typicode.com/photos?albumId=1')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = HTTParty.get("https://jsonplaceholder.typicode.com/users/#{params[:id]}")
    @album = HTTParty.get("https://jsonplaceholder.typicode.com/albums/#{params[:userId]}")
  end 
  
  def show
   @user = HTTParty.get("https://jsonplaceholder.typicode.com/users/#{params[:id]}")
   @album = HTTParty.get("https://jsonplaceholder.typicode.com/albums/#{params[:userId]}")
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<%= @users.class %>
<div data-controller="homepage" class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <% @albums.each do |album| %>  
        <div class="col">
            <% @users.each do |user| %>
                <% if user["id"] == album["id"]%>
                    <div class="card shadow-sm">
                        <%  @photos.each do |photo|%>
                            <% if photo["albumId"] == album["id"] %>
                                <%= image_tag photo["thumbnailUrl"], class:"card-img-top", width:"100%", height: 225 %>
                                <% break %>     
                            <% end %>    
                        <% end %>
                    
                        <div class="card-body">     
                            <p class="card-text">Full name: <%= user["name"] %></p>    
                                <h4>Album name: <%= album["title"] %></h4>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <%= link_to "user profile", api_v1_user_albums_path(user['id']), class:"btn btn-sm btn-outline-secondary",
                                                                                                        data: {
                                                                                                            homepage_target: "profile",
                                                                                                            }
                                    %>
                                    <%= link_to "gallery", api_v1_album_path(album['id']), class:"btn btn-sm btn-outline-secondary"%>
                                </div>
                                <small class="text-muted" class>9 mins</small>
                            </div>   
                        </div> 
                    </div> 
                <% end %>
            <% end %>
        </div>       
    <% end %>
</div>

app/views/albums/show.html.erb
<div class="container">
    <% @photos.each do |photo| %>
        <% if photo["albumId"] == @album["id"] %>
            <div class="container">
                <div class="row">              
                    <div class="col-md"><h4>Owners name: </h4><%= link_to @user["name"],user_path(@user['id'])  %></div>
                    <div class="col-md"><h6>Title: </h6><%= photo["title"] %></div>
                    <div class="col-md"><%= image_tag photo["url"], width:300, alt:"main image" %></div>
                </div>
                <hr>    
            </div>
        <% end %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
  
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

    <title>PhotographyPortfolioApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <%= link_to root_path, class:"navbar-brand d-flex align-items-center" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Album</strong>
          <% end %>
        </div>
      </div>
    </header>

    <section class="py-5 text-center container">
      <div class="row py-lg-2">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Photography Portfolio App</h1>
          
        </div>
      </div>
    </section>

    <div class="album py-5 bg-light">
      <div class="container">
        
          <%= yield %>
    
      </div>
    </div>  
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Photography Portfolio App &copy; Pawel Maryon</p>
      </div>
    </footer>
    <%# <script src="../assets/js/bootstrap.bundle.min.js"></script>  %>
    <script src="app/assets/stylesheets/bootstrap.bundle.min.js"></script> 
  </body>
</html>

</html>

app/views/photos/show.html.erb
<% @photos.each do |photo| %>
    <div class="container">
        <div class="row">
            <div class="col-md"><h4>AlbumId: </h4><%= photo['albumId'] %></div>
            <div class="col-md"><h5>Id: </h5><%= photo["id"] %></div>
            <div class="col-md"><h6>Title: </h6><%= photo["title"] %></div>
            <div class="col-md"><%= image_tag photo["url"], width:300, alt:"main image" %></div>
            <div class="col-md"><%= image_tag photo["thumbnailUrl"],width:150, alt:"thumbnail" %></div>
        </div>
        <hr>    
    </div>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <div class="borderbox">
        <%= link_to user_path(user['id']) do %>
            <h1>Full name: <%= user["name"] %></h1>
        <%end %>
        <h2>User: <%= user["username"] %></h2>
        <h3>Address:</h3> 
        <div class="row box-margin">
            <div class="borderbox col-sm-5 brd-box-margin">
                <div>
                    <p>street: <%= user["address"]["street"]%></p>
                    <p>house No: <%= user["address"]["suite"]%></p>
                    <p>city: <%= user["address"]["city"]%></p>
                    <p>zipcode: <%= user["address"]["zipcode"]%></p>
                </div>
            </div>
            <div class="borderbox col-6 ">
                <p>lat: <%= user["address"]["geo"]["lat"] %></p>
                <p>lng: <%= user["address"]["geo"]["lng"] %></p>
            </div>
        </div>
            <h3>Website:</h3> 
        <div class="borderbox">
            <p><%= user["website"] %></p>
        </div>
            <h3>Company: </h3>    
        <div class="borderbox">
            <p>Name: <%= user["company"]["name"] %></p>
            <p>Catch phrase: <%= user["company"]["catchPhrase"] %></p>
            <p>Bs: <%= user["company"]["bs"] %></p>
        </div>
        <h3>Phone number:</h3>
        <div class="borderbox">
            <p><%= user["phone"] %></p>
        </div>
        <h3>Titles: </h3>
        <div class="borderbox col-md">
            <ol>
                <% @album.each do |a| %>
                    <% if a["userId"] == user["id"] %>
                        <div class="row">
                            <li class="col-md"><%= link_to a["title"], album_path(a['id']) %></li>
                        </div>
                    <% end %>
                <% end %>
            </ol>
        </div>    
    </div>
<% end %>

app/views/users/show.html.erb
<main class="container">
  <div class="row p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-7 px-0">
        <div class="user-info">
        <h1 class="display-4 fst-italic">Full name: <%= @user["name"] %></h1>
        <h2 class="lead my-3">User: <%= @user["username"] %></h2>
        <h3>Address:</h3>
        <p>street: <%= @user["address"]["street"]%></p>
        <p>house No: <%= @user["address"]["suite"]%></p>
        <p>city: <%= @user["address"]["city"]%></p>
        <p>zipcode: <%= @user["address"]["zipcode"]%></p>
        <h3 class="lead mb-0 text-white fw-bold">Website:</h3>
        <p><%= @user["website"] %></p>
        <h3 class="lead mb-0 text-white fw-bold">Company: </h3>
        <p>Name: <%= @user["company"]["name"] %></p>
        <p>Catch phrase: <%= @user["company"]["catchPhrase"] %></p>
        <p>Bs: <%= @user["company"]["bs"] %></p>
        <h3 class="lead mb-0 text-white fw-bold">Phone number:</h3>
        <p><%= @user["phone"] %></p>
      </div>
    </div>
    <div class="col-md-5 px-0">
      <p>lat: <%= @user["address"]["geo"]["lat"] %></p>
      <p>lng: <%= @user["address"]["geo"]["lng"] %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4">
          <h4 class="fst-italic">Titles</h4>
          <ol class="list-unstyled mb-0">
            <li>
              <% @album.each do |a| %>
                <% if a["userId"] == @user["id"] %>
                  <div class="row">
                    <div class="col-md"><%= link_to a["title"], album_path(a['id']) %></div>
                  </div>
                <% end %>
              <% end %>
            </li>          
          </ol>
        </div>
      </div>
    </div>
  </div>
</main>